#!/opt/pyref/bin/python
"""Hermes independent CLI check: mixed M2/M3 edits, reloads, and exact pixels.

Does not use implementation-worker harnesses or test cases. IDs generated by
separate processes are mapped using the previously accepted M2 checker.
"""
import json
import os
import random
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, '/src/src')
from PIL import Image, ImageChops
from genko.io import load_episode, save_episode
from genko.models import PageSpec, new_episode
from genko.render import render_page
import m2_ops_check as shared

G = os.environ.get('GENKO_BIN', '/src/build/hermes-m3i-release/src/api/genko')
shared.GENKO = G
ROOT = Path(tempfile.mkdtemp(prefix='hermes-m3-mixed-'))
os.environ['GENKO_CONFIG_DIR'] = str(ROOT / 'config')


def cli(args, cpp):
    argv = [G, *map(str, args)] if cpp else [shared.PY, '-m', 'genko', *map(str, args)]
    code, reply, error = shared.run(argv)
    assert reply is not None, (argv, code, error)
    return code, reply


def snapshots(pybook, cppbook):
    a = cli(['inspect', pybook, '--full'], False)
    b = cli(['inspect', cppbook, '--full'], True)
    assert a[0] == b[0] == 0, (a, b)
    assert shared.norm(a[1], {}) == shared.norm(b[1], {}), ('snapshot mismatch', a, b)
    return a[1], b[1]


def ops_for(seed):
    rng = random.Random(seed)
    p = 1
    box = f'box-{seed}'
    man = f'man-{seed}'
    ruler = f'ruler-{seed}'
    effect = f'effect-{seed}'
    pts = [[round(rng.uniform(25, 120), 3), round(rng.uniform(25, 160), 3), 0.7] for _ in range(8)]
    return [
        [{'op': 'split_frame', 'page': p, 'axis': rng.choice(['horizontal', 'vertical']), 'ratio': 0.5, 'gutter_mm': 4}],
        [{'op': 'name_ok', 'page': p}, {'op': 'add_stroke', 'page': p, 'layer': 'ink', 'points': pts, 'kind': 'gpen', 'width_mm': 0.4}],
        [{'op': 'add_tone', 'page': p, 'density': rng.choice([0.1, 0.3, 0.5]), 'pattern': rng.choice(['dot', 'line', 'cross', 'flat']),
          'lpi': rng.choice([42.5, 60, 85]), 'angle': rng.choice([0, 15, 45]), 'area': {'rect': [20, 30, 45, 55]}}],
        [{'op': 'add_effect', 'page': p, 'id': effect, 'kind': 'focus', 'params': {'center': [70, 90], 'count': 30}}],
        [{'op': 'add_ruler', 'page': p, 'id': ruler, 'kind': 'line', 'points': [[25, 35], [100, 160]]},
         {'op': 'add_stroke', 'page': p, 'layer': 'ink', 'kind': 'gpen', 'points': pts, 'snap_ruler': ruler}],
        [{'op': 'ruler_to_layer', 'page': p, 'id': ruler, 'kind': 'gpen', 'width_mm': 0.4}],
        [{'op': 'add_prim3d', 'page': p, 'id': box, 'kind': rng.choice(['box', 'cylinder', 'stairs']),
          'pos': [80, 110, 0], 'size': [35, 40, 25], 'rot': [0.3, 0.6, 0]}],
        [{'op': 'add_mannequin', 'page': p, 'id': man, 'pos': [125, 140, 0], 'height_mm': 60},
         {'op': 'pose_mannequin', 'page': p, 'id': man, 'preset': rng.choice(['walk', 'sit', 'arms_up'])}],
        [{'op': 'trace_prims', 'page': p, 'ids': [box], 'layer': 'ink', 'kind': 'gpen', 'width_mm': 0.3}],
        [{'op': 'add_layer', 'page': p, 'id': f'pen-{seed}', 'kind': 'pen', 'name': '確認'},
         {'op': 'add_stroke', 'page': p, 'layer_id': f'pen-{seed}', 'kind': 'gpen', 'points': pts, 'width_mm': 0.5}],
        [{'op': 'set_camera', 'page': p, 'turn': 0.3, 'tip': 0.1, 'focal_mm': 120},
         {'op': 'set_light', 'page': p, 'dir': [0.2, 0.4, 0.6], 'ambient': 0.35}],
        [{'op': 'set_note', 'page': p, 'note': f'結合確認 {seed}'}, {'op': 'reorder', 'order': [1]}],
    ]


def main():
    counts = {'books': 0, 'steps_equal': 0, 'snapshots_equal': 0, 'renders_equal': 0}
    names = set()
    for n in range(int(sys.argv[1]) if len(sys.argv) > 1 else 8):
        seed = 8000 + n
        pybook = ROOT / f'py-{n}.genko'
        cppbook = ROOT / f'cpp-{n}.genko'
        ep = new_episode(f'結合 {seed}', 1, 1, PageSpec.b5_doujin())
        ep.pages[0].numero = False
        save_episode(ep, pybook, actor='human:確認')
        assert cli(['migrate', pybook, cppbook], True)[0] == 0
        for step, ops in enumerate(ops_for(seed)):
            a, b = snapshots(pybook, cppbook)
            mapping = {}
            shared.pair_ids(a, b, mapping)
            pfile, cfile = ROOT / 'py-ops.json', ROOT / 'cpp-ops.json'
            pfile.write_text(json.dumps(ops, ensure_ascii=False), encoding='utf-8')
            cfile.write_text(json.dumps(shared.translate(ops, mapping), ensure_ascii=False), encoding='utf-8')
            ra = cli(['apply', pybook, pfile, '--agent', 'human:確認'], False)
            rb = cli(['apply', cppbook, cfile, '--agent', 'human:確認'], True)
            assert ra[0] == rb[0] == 0, ('valid ops unexpectedly refused', seed, step, ops, ra, rb)
            assert shared.norm(ra[1], {}) == shared.norm(rb[1], {}), ('reply mismatch', seed, step, ra, rb)
            snapshots(pybook, cppbook)
            counts['steps_equal'] += 1
            counts['snapshots_equal'] += 1
            names.update(x['op'] for x in ops)
        ep = load_episode(pybook)
        for dpi in [72, 150]:
            for mode in ['print', 'proof', 'name']:
                image = ROOT / f'cpp-{n}-{dpi}-{mode}.png'
                code, result = cli(['render', cppbook, '--page', '1', '--dpi', dpi, '--mode', mode, '--out', image], True)
                assert code == 0, result
                ref = render_page(ep.pages[0], dpi, mode=mode, episode=ep).convert('RGB')
                got = Image.open(image).convert('RGB')
                assert got.size == ref.size, (seed, dpi, mode, 'size')
                assert ImageChops.difference(got, ref).getbbox() is None, (seed, dpi, mode, 'pixels')
                counts['renders_equal'] += 1
        counts['books'] += 1
        print(json.dumps({'progress': counts}, ensure_ascii=False), flush=True)
    print(json.dumps({**counts, 'ops': sorted(names), 'differences': 0}, ensure_ascii=False, indent=1))
    return 0


if __name__ == '__main__':
    sys.exit(main())
