#pragma once

// The fixed cases of contract/test_contract_tone_ops.cpp: each tone, effect and ruler op at least 8 times as it
// works and 4 times as it is refused, on the books tone_harness.py `fixture` makes ("A": fixture.genko; "B":
// strict.genko — strict_gates, page 2 locked by ai:other). $NAME is filled in from the book at run time (the ink
// square of panel f-bottom: $IN_X/$IN_Y inside it, $LINE_X/$LINE_Y on its left side; $MASK: a mask picture; $TILE:
// a tile picture).

namespace genko::test::tones {

struct Case {
    const char* op;     // the op the case is about
    char book;          // 'A' or 'B'
    const char* agent;
    bool works;         // the batch is applied (else refused)
    const char* ops;
};

// clang-format off
inline const Case kCases[] = {
    // --- add_tone ---
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 1, "id": "n1"}])"},
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 1, "id": "n2", "density": 0.45, "lpi": 85, "area": {"poly": [[12, 15], [70, 18], [65, 50], [15, 45]]}}])"},
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 1, "id": "n3", "pattern": "line", "angle": 15, "area": {"rect": [20, 30, 30.5, 20]}}])"},
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 1, "pattern": "cross", "dot_shape": "ellipse", "area": {"ellipse": [15, 60, 40, 25]}}])"},
    {"add_tone", 'A', "human:作者", true, R"([{"op": "add_tone", "page": 1, "id": "n5", "frame_id": "f-top", "gradient": {"shape": "radial", "start": 0, "end": 0.6}}])"},
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 1, "id": "n6", "at": {"x_mm": $IN_X, "y_mm": $IN_Y}, "density": 0.3}])"},
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 1, "id": "n7", "area": {"mask": {"box": [30, 40, 12.5, 9], "png": "$MASK"}}}])"},
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 1, "id": "n8", "pattern": "image", "tile_png": "$TILE", "scale_mm": 2, "frame_id": "f-bottom"}])"},
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 1, "id": "n9", "after": "t-dot", "name": "網2", "offset_mm": [0.5, -0.25], "move_by_mm": [0.25, 0.25]}])"},
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 1, "id": "n10", "pattern": "sand", "scale_mm": 1.5, "area": {"rect": [10, 10, 50, 40]}}])"},
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 1, "id": "n11", "at": {"x_mm": $IN_X, "y_mm": $IN_Y, "reference": "layer", "gap_mm": 1}}])"},
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 2, "id": "n12", "pattern": "flat", "density": 1, "lpi": 5, "angle": -30}])"},
    {"add_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 1, "id": "n13", "pattern": "star", "dot_shape": "round", "offset_mm": [0, 0], "area": {"poly": [[1, 1], [1, 1], [1, 1]]}}])"},
    {"add_tone", 'A', "genko", false, R"([{"op": "add_tone", "page": 1, "pattern": "stripes"}])"},
    {"add_tone", 'A', "genko", false, R"([{"op": "add_tone", "page": 1, "density": 1.5}])"},
    {"add_tone", 'A', "genko", false, R"([{"op": "add_tone", "page": 1, "id": "t-dot"}])"},
    {"add_tone", 'A', "genko", false, R"([{"op": "add_tone", "page": 1, "frame_id": "nope"}])"},
    {"add_tone", 'A', "genko", false, R"([{"op": "add_tone", "page": 1, "at": {"x_mm": $LINE_X, "y_mm": $LINE_Y}}])"},
    {"add_tone", 'A', "genko", false, R"([{"op": "add_tone", "page": 1, "area": {"poly": [[1, 2], [3, 4]]}}])"},
    {"add_tone", 'A', "genko", false, R"([{"op": "add_tone", "page": 1, "lpi": "abc"}])"},
    {"add_tone", 'A', "genko", false, R"([{"op": "add_tone", "page": 1, "pattern": "image"}])"},
    {"add_tone", 'A', "genko", false, R"([{"op": "add_tone", "page": 1, "gradient": {"start": 2}}])"},
    {"add_tone", 'A', "genko", false, R"([{"op": "add_tone", "page": 1, "offset_mm": "a"}])"},
    {"add_tone", 'B', "genko", false, R"([{"op": "add_tone", "page": 2}])"},
    // --- set_tone ---
    {"set_tone", 'A', "genko", true, R"([{"op": "set_tone", "page": 1, "id": "t-dot", "pattern": "line"}])"},
    {"set_tone", 'A', "genko", true, R"([{"op": "set_tone", "page": 1, "id": "t-dot", "gradient": {"shape": "linear", "angle": 60, "start": 0.2, "end": 0.9}, "density": 0.6}])"},
    {"set_tone", 'A', "genko", true, R"([{"op": "set_tone", "page": 1, "id": "t-img", "scale_mm": null, "tile_png": "$TILE"}])"},
    {"set_tone", 'A', "genko", true, R"([{"op": "set_tone", "page": 1, "id": "t-dot", "dot_shape": "square", "offset_mm": [1, 0.5]}])"},
    {"set_tone", 'A', "genko", true, R"([{"op": "set_tone", "page": 1, "id": "t-grad", "gradient": null, "lpi": 120, "angle": 75.5}])"},
    {"set_tone", 'A', "genko", true, R"([{"op": "set_tone", "page": 1, "id": "t-grad", "move_by_mm": [0.5, 0.5], "name": "斜線"}])"},
    {"set_tone", 'A', "genko", true, R"([{"op": "set_tone", "page": 1, "id": "t-dot", "dot_shape": null, "pattern": "noise", "scale_mm": 3}])"},
    {"set_tone", 'A', "ai:hermes", true, R"([{"op": "set_tone", "page": 1, "id": "t-img", "pattern": "brick", "scale_mm": 4.25, "density": 0.2}])"},
    {"set_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 2, "id": "p2"}, {"op": "set_tone", "page": 2, "id": "p2", "pattern": "wave", "offset_mm": [0, 0]}])"},
    {"set_tone", 'A', "genko", false, R"([{"op": "set_tone", "page": 1, "id": "ink", "density": 0.5}])"},
    {"set_tone", 'A', "genko", false, R"([{"op": "set_tone", "page": 1, "id": "nope"}])"},
    {"set_tone", 'A', "genko", false, R"([{"op": "set_tone", "page": 1, "id": "t-dot", "pattern": "stripes"}])"},
    {"set_tone", 'A', "genko", false, R"([{"op": "set_tone", "page": 1, "id": "t-dot", "dot_shape": "star"}])"},
    {"set_tone", 'A', "genko", false, R"([{"op": "set_tone", "page": 1, "id": "t-dot", "density": -0.1}])"},
    {"set_tone", 'A', "genko", false, R"([{"op": "set_tone", "page": 1, "id": "t-dot", "move_by_mm": [1, "x"]}])"},
    {"set_tone", 'A', "genko", false, R"([{"op": "set_tone", "page": 1}])"},
    {"set_tone", 'B', "ai:hermes", false, R"([{"op": "set_tone", "page": 2, "id": "x"}])"},
    // --- delete_tone ---
    {"delete_tone", 'A', "genko", true, R"([{"op": "delete_tone", "page": 1, "id": "t-dot"}])"},
    {"delete_tone", 'A', "genko", true, R"([{"op": "delete_tone", "page": 1, "id": "t-grad"}])"},
    {"delete_tone", 'A', "genko", true, R"([{"op": "delete_tone", "page": 1, "id": "t-img"}])"},
    {"delete_tone", 'A', "genko", true, R"([{"op": "delete_tone", "page": 1, "id": "ink"}])"},
    {"delete_tone", 'A', "genko", true, R"([{"op": "delete_tone", "page": 1, "id": "locked"}])"},
    {"delete_tone", 'A', "genko", true, R"([{"op": "add_tone", "page": 2, "id": "x"}, {"op": "delete_tone", "page": 2, "id": "x"}])"},
    {"delete_tone", 'A', "human:作者", true, R"([{"op": "delete_tone", "page": 1, "id": "t-dot"}, {"op": "delete_tone", "page": 1, "id": "t-img"}])"},
    {"delete_tone", 'B', "genko", true, R"([{"op": "delete_tone", "page": 1, "id": "t-grad"}])"},
    {"delete_tone", 'A', "genko", false, R"([{"op": "delete_tone", "page": 1, "id": "nope"}])"},
    {"delete_tone", 'A', "genko", false, R"([{"op": "delete_tone", "page": 1}])"},
    {"delete_tone", 'A', "genko", false, R"([{"op": "delete_tone", "page": 9, "id": "t-dot"}])"},
    {"delete_tone", 'A', "genko", false, R"([{"op": "delete_tone", "page": 1, "id": "t-dot"}, {"op": "delete_tone", "page": 1, "id": "t-dot"}])"},
    {"delete_tone", 'B', "genko", false, R"([{"op": "delete_tone", "page": 2, "id": "bg2"}])"},
    // --- add_effect ---
    {"add_effect", 'A', "genko", true, R"([{"op": "add_effect", "page": 1, "kind": "focus", "frame_id": "f-top", "id": "x1", "params": {"count": 40, "bundle": 5, "bundle_gap": 0.7, "jitter_position": 0}}])"},
    {"add_effect", 'A', "genko", true, R"([{"op": "add_effect", "page": 1, "kind": "speed", "id": "x2", "params": {"spacing_mm": 4, "curve": 5, "taper": "out"}}])"},
    {"add_effect", 'A', "genko", true, R"([{"op": "add_effect", "page": 1, "kind": "uni_flash", "frame_id": "f-bottom", "params": {"count": 50, "length_mm": 8, "jitter": 0.5}}])"},
    {"add_effect", 'A', "genko", true, R"([{"op": "add_effect", "page": 1, "kind": "beta_flash", "id": "x4", "params": {"spikes": 30, "depth": 0.8, "rgb": [200, 30, 30]}}])"},
    {"add_effect", 'A', "genko", true, R"([{"op": "add_effect", "page": 1, "kind": "white", "frame_id": "f-top", "id": "x5"}])"},
    {"add_effect", 'A', "genko", true, R"([{"op": "add_effect", "page": 1, "kind": "focus", "id": "x6", "params": {"center": [40, 30], "inner_path": [[30, 25], [50, 25], [45, 40]], "twist": 30, "length_mm": 10}}])"},
    {"add_effect", 'A', "genko", true, R"([{"op": "add_effect", "page": 1, "kind": "speed", "id": "x7", "params": {"path": [[15, 30], [45, 20], [75, 35]], "spread_mm": 12, "count": 15}}])"},
    {"add_effect", 'A', "genko", true, R"([{"op": "add_effect", "page": 1, "kind": "focus", "id": "x8", "params": {"avoid": [{"ellipse": [45, 40, 8, 6]}, {"path": [[20, 70], [40, 70], [30, 85]]}], "within": [[10, 10], [80, 12], [78, 100], [12, 98]], "jitter_width": 1}}])"},
    {"add_effect", 'A', "genko", true, R"([{"op": "add_effect", "page": 2, "kind": "speed", "params": {"angle": 90, "bundle": 3, "jitter_length": 0.3, "taper": false, "seed": "流"}}])"},
    {"add_effect", 'A', "genko", false, R"([{"op": "add_effect", "page": 1, "kind": "sparkle"}])"},
    {"add_effect", 'A', "genko", false, R"([{"op": "add_effect", "page": 1, "kind": "focus", "params": {"taper": "sideways"}}])"},
    {"add_effect", 'A', "genko", false, R"([{"op": "add_effect", "page": 1, "kind": "speed", "params": {"count": 5000}}])"},
    {"add_effect", 'A', "genko", false, R"([{"op": "add_effect", "page": 1, "kind": "speed", "frame_id": "nope"}])"},
    {"add_effect", 'A', "genko", false, R"([{"op": "add_effect", "page": 1, "kind": "focus", "params": {"jitter": 3}}])"},
    {"add_effect", 'A', "genko", false, R"([{"op": "add_effect", "page": 1, "kind": "focus", "params": {"avoid": [{"ellipse": [1, 2, 3]}]}}])"},
    {"add_effect", 'A', "genko", false, R"([{"op": "add_effect", "page": 1, "kind": "speed", "params": {"bundle": 0}}])"},
    {"add_effect", 'A', "genko", false, R"([{"op": "add_effect", "page": 1, "kind": "speed", "params": {"count": "many"}}])"},
    {"add_effect", 'B', "genko", false, R"([{"op": "add_effect", "page": 2, "kind": "speed"}])"},
    // --- edit_effect ---
    {"edit_effect", 'A', "genko", true, R"([{"op": "edit_effect", "page": 1, "id": "e-focus", "params": {"count": 80, "taper": "both"}}])"},
    {"edit_effect", 'A', "genko", true, R"([{"op": "edit_effect", "page": 1, "id": "e-focus", "params": {"count": null}}])"},
    {"edit_effect", 'A', "genko", true, R"([{"op": "edit_effect", "page": 1, "id": "e-speed", "kind": "focus"}])"},
    {"edit_effect", 'A', "genko", true, R"([{"op": "edit_effect", "page": 1, "id": "e-speed", "visible": false}])"},
    {"edit_effect", 'A', "genko", true, R"([{"op": "edit_effect", "page": 1, "id": "e-beta", "frame_id": "f-top"}])"},
    {"edit_effect", 'A', "genko", true, R"([{"op": "edit_effect", "page": 1, "id": "e-focus", "frame_id": null, "visible": 1}])"},
    {"edit_effect", 'A', "genko", true, R"([{"op": "edit_effect", "page": 1, "id": "e-beta", "params": {"seed": 7, "spikes": 44, "depth": 0.3}}])"},
    {"edit_effect", 'A', "genko", true, R"([{"op": "edit_effect", "page": 2, "id": "e2", "kind": "white", "params": {"rgb": [1, 2, 3]}}])"},
    {"edit_effect", 'A', "ai:hermes", true, R"([{"op": "edit_effect", "page": 1, "id": "e-speed", "params": {"path": [[10, 70], [80, 100]]}}])"},
    {"edit_effect", 'A', "genko", false, R"([{"op": "edit_effect", "page": 1, "id": "nope"}])"},
    {"edit_effect", 'A', "genko", false, R"([{"op": "edit_effect", "page": 1, "id": "e-focus", "params": {"jitter": 3}}])"},
    {"edit_effect", 'A', "genko", false, R"([{"op": "edit_effect", "page": 1, "id": "e-focus", "kind": "sparkle"}])"},
    {"edit_effect", 'A', "genko", false, R"([{"op": "edit_effect", "page": 1, "id": "e-focus", "frame_id": "nope"}])"},
    {"edit_effect", 'A', "genko", false, R"([{"op": "edit_effect", "page": 1, "id": "e-focus", "params": 5}])"},
    {"edit_effect", 'B', "genko", false, R"([{"op": "edit_effect", "page": 2, "id": "e2"}])"},
    // --- delete_effect ---
    {"delete_effect", 'A', "genko", true, R"([{"op": "delete_effect", "page": 1, "id": "e-focus"}])"},
    {"delete_effect", 'A', "genko", true, R"([{"op": "delete_effect", "page": 1, "id": "e-speed"}])"},
    {"delete_effect", 'A', "genko", true, R"([{"op": "delete_effect", "page": 1, "id": "e-beta"}])"},
    {"delete_effect", 'A', "genko", true, R"([{"op": "delete_effect", "page": 2, "id": "e2"}])"},
    {"delete_effect", 'A', "genko", true, R"([{"op": "add_effect", "page": 1, "kind": "white", "id": "e-focus"}, {"op": "delete_effect", "page": 1, "id": "e-focus"}])"},
    {"delete_effect", 'A', "human:作者", true, R"([{"op": "delete_effect", "page": 1, "id": "e-focus"}, {"op": "delete_effect", "page": 1, "id": "e-beta"}])"},
    {"delete_effect", 'B', "genko", true, R"([{"op": "delete_effect", "page": 1, "id": "e-speed"}])"},
    {"delete_effect", 'A', "ai:hermes", true, R"([{"op": "delete_effect", "page": 1, "id": "e-speed"}])"},
    {"delete_effect", 'A', "genko", false, R"([{"op": "delete_effect", "page": 1, "id": "nope"}])"},
    {"delete_effect", 'A', "genko", false, R"([{"op": "delete_effect", "page": 1}])"},
    {"delete_effect", 'A', "genko", false, R"([{"op": "delete_effect", "page": 2, "id": "e-focus"}])"},
    {"delete_effect", 'B', "genko", false, R"([{"op": "delete_effect", "page": 2, "id": "e2"}])"},
    // --- effect_to_layer ---
    {"effect_to_layer", 'A', "genko", true, R"([{"op": "effect_to_layer", "page": 1, "id": "e-focus"}])"},
    {"effect_to_layer", 'A', "genko", true, R"([{"op": "effect_to_layer", "page": 1, "id": "e-speed", "layer_id": "ink"}])"},
    {"effect_to_layer", 'A', "genko", true, R"([{"op": "effect_to_layer", "page": 1, "id": "e-beta", "layer": "finish"}])"},
    {"effect_to_layer", 'A', "genko", true, R"([{"op": "effect_to_layer", "page": 1, "id": "e-focus", "keep": true, "layer": "name"}])"},
    {"effect_to_layer", 'A', "genko", true, R"([{"op": "effect_to_layer", "page": 1, "id": "e-speed", "layer_id": "t-dot"}])"},
    {"effect_to_layer", 'A', "genko", true, R"([{"op": "effect_to_layer", "page": 2, "id": "e2", "layer": "draft"}])"},
    {"effect_to_layer", 'A', "genko", true, R"([{"op": "add_effect", "page": 1, "kind": "focus", "id": "c", "params": {"count": 20, "avoid": [{"ellipse": [45, 40, 10, 8]}], "rgb": [255, 255, 255]}}, {"op": "effect_to_layer", "page": 1, "id": "c"}])"},
    {"effect_to_layer", 'B', "genko", true, R"([{"op": "effect_to_layer", "page": 1, "id": "e-focus", "layer_id": "name"}])"},
    {"effect_to_layer", 'B', "genko", true, R"([{"op": "name_ok", "page": 1}, {"op": "effect_to_layer", "page": 1, "id": "e-speed"}])"},
    {"effect_to_layer", 'A', "genko", false, R"([{"op": "effect_to_layer", "page": 1, "id": "nope"}])"},
    {"effect_to_layer", 'A', "genko", false, R"([{"op": "effect_to_layer", "page": 1, "id": "e-focus", "layer": "bogus"}])"},
    {"effect_to_layer", 'A', "genko", false, R"([{"op": "effect_to_layer", "page": 1, "id": "e-focus", "layer_id": "bg"}])"},
    {"effect_to_layer", 'A', "genko", false, R"([{"op": "effect_to_layer", "page": 1, "id": "e-focus", "layer_id": "locked"}])"},
    {"effect_to_layer", 'B', "genko", false, R"([{"op": "effect_to_layer", "page": 1, "id": "e-focus"}])"},
    {"effect_to_layer", 'B', "genko", false, R"([{"op": "effect_to_layer", "page": 1, "id": "e-focus", "layer_id": "ink"}])"},
    {"effect_to_layer", 'B', "genko", false, R"([{"op": "effect_to_layer", "page": 2, "id": "e2"}])"},
    // --- add_ruler ---
    {"add_ruler", 'A', "genko", true, R"([{"op": "add_ruler", "page": 1, "kind": "line", "points": [[20, 100], [200, 160]], "id": "a1"}])"},
    {"add_ruler", 'A', "genko", true, R"([{"op": "add_ruler", "page": 1, "kind": "guide", "axis": "v", "at": 64.12345}])"},
    {"add_ruler", 'A', "genko", true, R"([{"op": "add_ruler", "page": 1, "kind": "symmetry", "points": [[45, 0], [45, 100]], "copies": 6, "mirror": 1, "id": "a3"}])"},
    {"add_ruler", 'A', "genko", true, R"([{"op": "add_ruler", "page": 1, "kind": "perspective", "points": [[-80, 70], [260, 70], [45, 400]], "grid": 6, "lock_horizon": true, "id": "a4"}])"},
    {"add_ruler", 'A', "genko", true, R"([{"op": "add_ruler", "page": 1, "kind": "concentric", "points": [[45, 60]], "ratio": 0.5, "angle": 30, "reach_mm": 5, "id": "a5"}])"},
    {"add_ruler", 'A', "genko", true, R"([{"op": "add_ruler", "page": 1, "kind": "multi_curve", "points": [[0, 0], [100, 0]], "points2": [[0, 100], [50, 140], [100, 100]], "id": "a6"}])"},
    {"add_ruler", 'A', "genko", true, R"([{"op": "add_ruler", "page": 1, "kind": "radial_curve", "points": [[0, 0], [50, 20], [100, 0]], "center": [50, -100], "frame_id": "f-top", "id": "a7"}])"},
    {"add_ruler", 'A', "genko", true, R"([{"op": "add_ruler", "page": 1, "kind": "ellipse", "points": [[20, 20], [60, 45.5]], "angle": 12.3456, "layer_id": "ink", "id": "a8"}])"},
    {"add_ruler", 'A', "genko", true, R"([{"op": "add_ruler", "page": 2, "kind": "polygon", "points": [[0, 0], [30, 0], [15, 20]], "active": 0, "visible": false, "fixed": "yes"}])"},
    {"add_ruler", 'A', "genko", true, R"([{"op": "add_ruler", "page": 1, "kind": "parallel_curve", "points": [[10, 10], [40, 30], [80, 10]], "grid": 0, "layer_id": null, "frame_id": ""}])"},
    {"add_ruler", 'A', "genko", false, R"([{"op": "add_ruler", "page": 1, "kind": "spiral"}])"},
    {"add_ruler", 'A', "genko", false, R"([{"op": "add_ruler", "page": 1, "kind": "line", "points": [[1, 1]]}])"},
    {"add_ruler", 'A', "genko", false, R"([{"op": "add_ruler", "page": 1, "kind": "guide", "axis": "z", "at": 1}])"},
    {"add_ruler", 'A', "genko", false, R"([{"op": "add_ruler", "page": 1, "kind": "line", "points": [[1, 1], [2, 2]], "id": "r-line"}])"},
    {"add_ruler", 'A', "genko", false, R"([{"op": "add_ruler", "page": 1, "kind": "parallel", "frame_id": "nope"}])"},
    {"add_ruler", 'A', "genko", false, R"([{"op": "add_ruler", "page": 1, "kind": "parallel", "layer_id": "nope"}])"},
    {"add_ruler", 'A', "genko", false, R"([{"op": "add_ruler", "page": 1, "kind": "symmetry", "points": [[1, 1], [2, 2]], "copies": 40}])"},
    {"add_ruler", 'A', "genko", false, R"([{"op": "add_ruler", "page": 1, "kind": "rect", "points": [[0, 0], [0.2, 10]]}])"},
    {"add_ruler", 'A', "genko", false, R"([{"op": "add_ruler", "page": 1, "kind": "guide", "axis": "h"}])"},
    {"add_ruler", 'B', "genko", false, R"([{"op": "add_ruler", "page": 2, "kind": "parallel"}])"},
    // --- edit_ruler ---
    {"edit_ruler", 'A', "genko", true, R"([{"op": "edit_ruler", "page": 1, "id": "r-line", "points": [[12.3456, 20], [80, 33.3333]]}])"},
    {"edit_ruler", 'A', "genko", true, R"([{"op": "edit_ruler", "page": 1, "id": "r-persp", "points": [[-40, 55], [150, 35]]}])"},
    {"edit_ruler", 'A', "genko", true, R"([{"op": "edit_ruler", "page": 1, "id": "r-persp", "horizon_y": 25.5}])"},
    {"edit_ruler", 'A', "genko", true, R"([{"op": "edit_ruler", "page": 1, "id": "r-fixed", "fixed": false, "points": [[30, 15]]}])"},
    {"edit_ruler", 'A', "genko", true, R"([{"op": "edit_ruler", "page": 1, "id": "r-conc", "ratio": 2, "angle": -20, "active": false}])"},
    {"edit_ruler", 'A', "genko", true, R"([{"op": "edit_ruler", "page": 1, "id": "r-persp", "grid": 8, "layer_id": "ink", "frame_id": "f-top"}])"},
    {"edit_ruler", 'A', "genko", true, R"([{"op": "edit_ruler", "page": 1, "id": "r-sym", "copies": 4, "mirror": true, "frame_id": null}])"},
    {"edit_ruler", 'A', "genko", true, R"([{"op": "edit_ruler", "page": 1, "id": "r-guide", "at": 70, "axis": "v", "reach_mm": 2}])"},
    {"edit_ruler", 'A', "ai:hermes", true, R"([{"op": "edit_ruler", "page": 1, "id": "r-rect", "points": [[25, 25], [70, 50]], "angle": 0}])"},
    {"edit_ruler", 'A', "genko", true, R"([{"op": "edit_ruler", "page": 1, "id": "r-fixed", "horizon_y": 30, "fixed": false}])"},
    {"edit_ruler", 'A', "genko", false, R"([{"op": "edit_ruler", "page": 1, "id": "nope"}])"},
    {"edit_ruler", 'A', "genko", false, R"([{"op": "edit_ruler", "page": 1, "id": "r-fixed", "points": [[0, 0]]}])"},
    {"edit_ruler", 'A', "genko", false, R"([{"op": "edit_ruler", "page": 1, "id": "r-persp", "grid": 61}])"},
    {"edit_ruler", 'A', "genko", false, R"([{"op": "edit_ruler", "page": 1, "id": "r-conc", "ratio": -1}])"},
    {"edit_ruler", 'A', "genko", false, R"([{"op": "edit_ruler", "page": 1, "id": "r-line", "points": [[1, 1]]}])"},
    {"edit_ruler", 'A', "genko", false, R"([{"op": "edit_ruler", "page": 1, "id": "r-persp", "horizon_y": "up"}])"},
    {"edit_ruler", 'B', "genko", false, R"([{"op": "edit_ruler", "page": 2, "id": "r2"}])"},
    // --- delete_ruler ---
    {"delete_ruler", 'A', "genko", true, R"([{"op": "delete_ruler", "page": 1, "id": "r-line"}])"},
    {"delete_ruler", 'A', "genko", true, R"([{"op": "delete_ruler", "page": 1}])"},
    {"delete_ruler", 'A', "genko", true, R"([{"op": "delete_ruler", "page": 2, "id": "r2"}])"},
    {"delete_ruler", 'A', "genko", true, R"([{"op": "delete_ruler", "page": 2}])"},
    {"delete_ruler", 'A', "genko", true, R"([{"op": "delete_ruler", "page": 1, "id": "r-persp"}, {"op": "delete_ruler", "page": 1, "id": "r-fixed"}])"},
    {"delete_ruler", 'A', "genko", true, R"([{"op": "add_ruler", "page": 1, "kind": "parallel", "id": "z"}, {"op": "delete_ruler", "page": 1, "id": "z"}])"},
    {"delete_ruler", 'A', "ai:hermes", true, R"([{"op": "delete_ruler", "page": 1, "id": ""}])"},
    {"delete_ruler", 'B', "genko", true, R"([{"op": "delete_ruler", "page": 1, "id": "r-guide"}])"},
    {"delete_ruler", 'A', "genko", false, R"([{"op": "delete_ruler", "page": 1, "id": "nope"}])"},
    {"delete_ruler", 'A', "genko", false, R"([{"op": "delete_ruler", "page": 9}])"},
    {"delete_ruler", 'A', "genko", false, R"([{"op": "delete_ruler", "page": 1, "id": "r2"}])"},
    {"delete_ruler", 'B', "genko", false, R"([{"op": "delete_ruler", "page": 2}])"},
    // --- set_ruler ---
    {"set_ruler", 'A', "genko", true, R"([{"op": "set_ruler", "page": 1, "kind": "perspective", "points": [[100, 20]]}])"},
    {"set_ruler", 'A', "genko", true, R"([{"op": "set_ruler", "page": 1, "points": [[40, 20], [170, 20]]}])"},
    {"set_ruler", 'A', "genko", true, R"([{"op": "set_ruler", "page": 1, "kind": "line"}])"},
    {"set_ruler", 'A', "genko", true, R"([{"op": "set_ruler", "page": 2, "kind": "", "points": []}])"},
    {"set_ruler", 'A', "genko", true, R"([{"op": "set_ruler", "page": 1, "points": ["ab", [1, 2, 3]]}])"},
    {"set_ruler", 'A', "genko", true, R"([{"op": "set_ruler", "page": 1, "kind": 5, "points": [{"x": 1, "y": 2}]}])"},
    {"set_ruler", 'A', "ai:hermes", true, R"([{"op": "set_ruler", "page": 1, "points": null}])"},
    {"set_ruler", 'B', "genko", true, R"([{"op": "set_ruler", "page": 1, "points": [[45.25, 10.5]]}])"},
    {"set_ruler", 'A', "genko", false, R"([{"op": "set_ruler", "page": 1, "points": [5]}])"},
    {"set_ruler", 'A', "genko", false, R"([{"op": "set_ruler", "page": 1, "points": 7}])"},
    {"set_ruler", 'A', "genko", false, R"([{"op": "set_ruler", "points": [[1, 2]]}])"},
    {"set_ruler", 'B', "genko", false, R"([{"op": "set_ruler", "page": 2, "points": []}])"},
    // --- ruler_to_layer ---
    {"ruler_to_layer", 'A', "genko", true, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-line"}])"},
    {"ruler_to_layer", 'A', "genko", true, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-curve", "width_mm": 0.3}])"},
    {"ruler_to_layer", 'A', "genko", true, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-rect", "kind": "gpen", "rgb": [200, 10, 10]}])"},
    {"ruler_to_layer", 'A', "genko", true, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-conc", "layer": "finish"}])"},
    {"ruler_to_layer", 'A', "genko", true, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-guide", "layer_id": "t-dot", "kind": "oil"}])"},
    {"ruler_to_layer", 'A', "genko", true, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-persp", "layer": "name", "rgb": [1, 2, 3, 4]}])"},
    {"ruler_to_layer", 'A', "genko", true, R"([{"op": "add_ruler", "page": 1, "kind": "ellipse", "points": [[10, 10], [50, 30]], "id": "el"}, {"op": "ruler_to_layer", "page": 1, "id": "el", "width_mm": 0}])"},
    {"ruler_to_layer", 'A', "genko", true, R"([{"op": "ruler_to_layer", "page": 2, "id": "r2", "layer": "draft"}])"},
    {"ruler_to_layer", 'B', "genko", true, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-line", "layer_id": "finish"}])"},
    {"ruler_to_layer", 'A', "genko", false, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-par"}])"},
    {"ruler_to_layer", 'A', "genko", false, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-line", "kind": "bogus"}])"},
    {"ruler_to_layer", 'A', "genko", false, R"([{"op": "ruler_to_layer", "page": 1, "id": "nope"}])"},
    {"ruler_to_layer", 'A', "genko", false, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-line", "layer": "bogus"}])"},
    {"ruler_to_layer", 'A', "genko", false, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-line", "layer_id": "locked"}])"},
    {"ruler_to_layer", 'A', "genko", false, R"([{"op": "ruler_to_layer", "page": 1, "id": "r-line", "width_mm": "w"}])"},
    {"ruler_to_layer", 'B', "genko", false, R"([{"op": "ruler_to_layer", "page": 2, "id": "r2"}])"},
};
// clang-format on

}  // namespace genko::test::tones
